version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: business_management_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: business_management_database
      POSTGRES_USER: SuperAdminBM
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U SuperAdminBM -d business_management_database"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bm_network
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: bm_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bm.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bm_network
    depends_on:
      postgres:
        condition: service_healthy
    
volumes:
  postgres_data:
  pgadmin_data:

networks:
  bm_network:
    name: business_management_network
    driver: bridge
